"""Add monitoring models and job fields

Revision ID: a91b9287e9f3
Revises: 3a2540e6f658
Create Date: 2026-08-29 14:41:40.606201+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a91b9287e9f3'
down_revision: Union[str, None] = '3a2540e6f658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_schedules',
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=2000), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('match_threshold', sa.Float(), nullable=False),
    sa.Column('max_preparations_per_cycle', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_schedules_user_id'), ['user_id'], unique=False)

    op.create_table('monitoring_runs',
    sa.Column('schedule_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('jobs_found', sa.Integer(), nullable=False),
    sa.Column('jobs_new', sa.Integer(), nullable=False),
    sa.Column('jobs_eligible', sa.Integer(), nullable=False),
    sa.Column('jobs_matched', sa.Integer(), nullable=False),
    sa.Column('jobs_selected', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['monitoring_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_runs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('application_approvals', schema=None) as batch_op:
        batch_op.create_index('idx_app_approval_application', ['application_id'], unique=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canonical_url', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('first_seen_at')
        batch_op.drop_column('content_hash')
        batch_op.drop_column('canonical_url')

    with op.batch_alter_table('application_approvals', schema=None) as batch_op:
        batch_op.drop_index('idx_app_approval_application')

    with op.batch_alter_table('monitoring_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_runs_user_id'))

    op.drop_table('monitoring_runs')
    with op.batch_alter_table('monitoring_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_schedules_user_id'))

    op.drop_table('monitoring_schedules')
    # ### end Alembic commands ###
