"""job_data_quality_fields

Revision ID: e789fc8b2d97
Revises: adc3a2aa1a61
Create Date: 2026-09-04 10:03:38.247686+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e789fc8b2d97'
down_revision: Union[str, None] = 'adc3a2aa1a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_normalized', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('extraction_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('data_quality_flags', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('data_quality_flags')
        batch_op.drop_column('extraction_confidence')
        batch_op.drop_column('is_normalized')

    # ### end Alembic commands ###

