"""Add tailoring session models

Revision ID: b9937cfce40e
Revises: e789fc8b2d97
Create Date: 2026-09-04 16:53:29.957485+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b9937cfce40e'
down_revision: Union[str, None] = 'e789fc8b2d97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_tailoring_sessions',
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('base_resume_id', sa.String(length=32), nullable=False),
    sa.Column('base_resume_version', sa.String(length=50), nullable=True),
    sa.Column('candidate_profile_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('draft', 'reviewing', 'approved', 'rendering', 'verified', 'failed', name='tailoring_status'), nullable=False),
    sa.Column('tailor_model', sa.String(length=100), nullable=True),
    sa.Column('review_model', sa.String(length=100), nullable=True),
    sa.Column('final_resume_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['base_resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['final_resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cv_tailoring_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cv_tailoring_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_tailoring_status', ['status'], unique=False)

    op.create_table('cv_tailoring_changes',
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('change_id', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_reference', sa.String(length=200), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('proposed_text', sa.Text(), nullable=True),
    sa.Column('change_type', sa.Enum('add', 'modify', 'remove', name='change_type'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('linked_requirement_ids', sa.JSON(), nullable=False),
    sa.Column('linked_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('review_severity', sa.Enum('safe', 'warning', 'blocked', name='review_severity'), nullable=False),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('user_decision', sa.Enum('pending', 'accepted', 'rejected', name='reviewer_status'), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['cv_tailoring_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cv_tailoring_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cv_tailoring_changes_user_id'), ['user_id'], unique=False)



    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('cv_tailoring_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cv_tailoring_changes_user_id'))

    op.drop_table('cv_tailoring_changes')
    with op.batch_alter_table('cv_tailoring_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_tailoring_status')
        batch_op.drop_index(batch_op.f('ix_cv_tailoring_sessions_user_id'))

    op.drop_table('cv_tailoring_sessions')
    # ### end Alembic commands ###

