"""Add ApplicationRoute and Job provenance fields

Revision ID: 46466006b1d5
Revises: 5938f1704db6
Create Date: 2026-08-29 20:02:33.991431+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '46466006b1d5'
down_revision: Union[str, None] = '5938f1704db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_routes',
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('route_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('resolution_reason', sa.String(length=500), nullable=True),
    sa.Column('requires_human', sa.Boolean(), nullable=False),
    sa.Column('is_preferred', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_routes_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('source_reference', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('raw_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('raw_source_payload', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('received_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('received_at')
        batch_op.drop_column('raw_source_payload')
        batch_op.drop_column('raw_text')
        batch_op.drop_column('source_reference')
        batch_op.drop_column('source_type')

    with op.batch_alter_table('application_routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_routes_user_id'))

    op.drop_table('application_routes')
    # ### end Alembic commands ###
