"""Phase 18 Unified Intake

Revision ID: 68fdbbe17245
Revises: b9937cfce40e
Create Date: 2026-09-06 14:36:11.197429+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '68fdbbe17245'
down_revision: Union[str, None] = 'b9937cfce40e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_routes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_overridden', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('overridden_by_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detected_language', sa.String(length=20), nullable=True))
        batch_op.alter_column('is_normalized',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('new', 'saved', 'applied', 'hidden', 'received', 'processing', 'ready', 'needs_review', 'failed', 'duplicate', name='job_status'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('new', 'saved', 'applied', 'hidden', 'received', 'processing', 'ready', 'needs_review', 'failed', 'duplicate', name='job_status'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
        batch_op.alter_column('is_normalized',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.drop_column('detected_language')

    with op.batch_alter_table('application_routes', schema=None) as batch_op:
        batch_op.drop_column('overridden_at')
        batch_op.drop_column('overridden_by_id')
        batch_op.drop_column('user_overridden')

    # ### end Alembic commands ###
