"""Add Autonomous Discovery Models

Revision ID: 4a0079502a9d
Revises: 46466006b1d5
Create Date: 2026-08-29 20:16:29.308785+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '4a0079502a9d'
down_revision: Union[str, None] = '46466006b1d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_watches',
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('match_threshold', sa.Float(), nullable=False),
    sa.Column('max_preparations_per_cycle', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_watches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_watches_user_id'), ['user_id'], unique=False)

    op.create_table('search_profiles',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target_roles', sa.JSON(), nullable=False),
    sa.Column('role_aliases', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('excluded_keywords', sa.JSON(), nullable=False),
    sa.Column('preferred_countries', sa.JSON(), nullable=False),
    sa.Column('preferred_cities', sa.JSON(), nullable=False),
    sa.Column('preferred_work_models', sa.JSON(), nullable=False),
    sa.Column('employment_types', sa.JSON(), nullable=False),
    sa.Column('seniority', sa.JSON(), nullable=False),
    sa.Column('excluded_companies', sa.JSON(), nullable=False),
    sa.Column('preferred_companies', sa.JSON(), nullable=False),
    sa.Column('minimum_match_score', sa.Float(), nullable=False),
    sa.Column('max_preparations_per_cycle', sa.Integer(), nullable=False),
    sa.Column('max_preparations_per_day', sa.Integer(), nullable=False),
    sa.Column('frequency_minutes', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('discovery_events',
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('discovery_provider', sa.String(length=50), nullable=False),
    sa.Column('discovery_query', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discovery_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovery_events_user_id'), ['user_id'], unique=False)

    op.create_table('discovery_runs',
    sa.Column('search_profile_id', sa.String(length=32), nullable=True),
    sa.Column('company_watch_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('provider_errors', sa.JSON(), nullable=True),
    sa.Column('queries_generated', sa.Integer(), nullable=False),
    sa.Column('jobs_found', sa.Integer(), nullable=False),
    sa.Column('jobs_new', sa.Integer(), nullable=False),
    sa.Column('jobs_eligible', sa.Integer(), nullable=False),
    sa.Column('jobs_matched', sa.Integer(), nullable=False),
    sa.Column('jobs_selected', sa.Integer(), nullable=False),
    sa.Column('skipped_reasons', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['company_watch_id'], ['company_watches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_profile_id'], ['search_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discovery_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovery_runs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('monitoring_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_schedules_user_id'))

    op.drop_table('monitoring_schedules')
    with op.batch_alter_table('monitoring_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_runs_user_id'))

    op.drop_table('monitoring_runs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_runs',
    sa.Column('schedule_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('duration', sa.FLOAT(), nullable=True),
    sa.Column('error', sa.TEXT(), nullable=True),
    sa.Column('jobs_found', sa.INTEGER(), nullable=False),
    sa.Column('jobs_new', sa.INTEGER(), nullable=False),
    sa.Column('jobs_eligible', sa.INTEGER(), nullable=False),
    sa.Column('jobs_matched', sa.INTEGER(), nullable=False),
    sa.Column('jobs_selected', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['monitoring_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_runs_user_id'), ['user_id'], unique=False)

    op.create_table('monitoring_schedules',
    sa.Column('platform', sa.VARCHAR(length=50), nullable=False),
    sa.Column('source', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('interval_minutes', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('last_checked_at', sa.DATETIME(), nullable=True),
    sa.Column('match_threshold', sa.FLOAT(), nullable=False),
    sa.Column('max_preparations_per_cycle', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_schedules_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('discovery_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovery_runs_user_id'))

    op.drop_table('discovery_runs')
    with op.batch_alter_table('discovery_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovery_events_user_id'))

    op.drop_table('discovery_events')
    with op.batch_alter_table('search_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_profiles_user_id'))

    op.drop_table('search_profiles')
    with op.batch_alter_table('company_watches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_watches_user_id'))

    op.drop_table('company_watches')
    # ### end Alembic commands ###
