"""Add ApplicationApproval model

Revision ID: 3a2540e6f658
Revises: 572d66654281
Create Date: 2026-08-22 11:38:07.748387+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '3a2540e6f658'
down_revision: Union[str, None] = '572d66654281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_approvals',
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('application_run_id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('candidate_profile_version', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['application_run_id'], ['application_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_approvals', schema=None) as batch_op:
        batch_op.create_index('ix_app_approval_run', ['application_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_approvals_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_app_approval_single_use', ['application_id'], unique=True)

    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.alter_column('languages',
               existing_type=sqlite.JSON(),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.alter_column('languages',
               existing_type=sqlite.JSON(),
               server_default=sa.text("'[]'"),
               existing_nullable=False)

    with op.batch_alter_table('application_approvals', schema=None) as batch_op:
        batch_op.drop_index('uq_app_approval_single_use')
        batch_op.drop_index(batch_op.f('ix_application_approvals_user_id'))
        batch_op.drop_index('ix_app_approval_run')

    op.drop_table('application_approvals')
    # ### end Alembic commands ###
