"""add_application_run

Revision ID: b8ba9b214c91
Revises: d4d778fd4d42
Create Date: 2026-08-19 19:58:33.505111+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b8ba9b214c91'
down_revision: Union[str, None] = 'd4d778fd4d42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_runs',
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('state_data', sa.JSON(), nullable=True),
    sa.Column('artifacts', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_runs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.Enum('discovered', 'matched', 'preparing', 'ready', 'waiting_for_review', 'queued', 'pending_review', 'approved', 'applying', 'applied', 'interview', 'rejected', 'offer', 'withdrawn', 'failed', name='application_status'),
               existing_nullable=False)

    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('discovered', 'matched', 'preparing', 'ready', 'waiting_for_review', 'queued', 'pending_review', 'approved', 'applying', 'applied', 'interview', 'rejected', 'offer', 'withdrawn', 'failed', name='application_status'),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)

    with op.batch_alter_table('application_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_runs_user_id'))

    op.drop_table('application_runs')
    # ### end Alembic commands ###
